notifications:
  email: false
language: node_js
node_js:
  - "10"
script:
  - npm run build
deploy:
  provider: surge
  project: ./dist
  domain: https://nbenakis.surge.sh/
  skip-cleanup: true
  on:
    branch: master
after_success:
  - "curl -Lo travis_after_all.py https://git.io/travis_after_all"
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
branches:
  only:
    - master
