sudo: required
notifications:
  email: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "latest"
before_script:
  - sudo $(which npm) install
script:
  - sudo $(which npm) run build
after_success:
  - "curl -Lo travis_after_all.py https://git.io/travis_after_all"
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
branches:
  only:
    - master
