sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
before_install:
  - npm install -g
  - npm ci
script:
  - npm run build
deploy:
  provider: surge
  project: ./dist
  domain: https://nbenakis.surge.sh/
  skip-cleanup: true
  on:
    branch: master
